name: Update Database

on:
  schedule:
    - cron: "*/15 * * * *"  # Run every 15 minutes
  workflow_dispatch:  # Allow manual triggering

jobs:
  update_db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run update_db.py
        env:
          DEPLOYMENT_ID_1: ${{ secrets.DEPLOYMENT_ID_1 }}
          DEPLOYMENT_ID_2: ${{ secrets.DEPLOYMENT_ID_2 }}  # Add more if needed
        run: python update_db.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add database/database.db db_version.json
          if ! git diff --cached --quiet; then
            git commit -m "Update database and version"
            git push
          fi
